package io.sinaq.api.context;

import io.sinaq.api.internal.context.DefaultRequestContext;
import java.util.Map;
import java.util.Optional;

/**
 * Per-request execution context: identifies one HTTP call for logging,
 * events and error reporting.
 *
 * <p>Implementations must be immutable and safe to share between threads.
 * Phase 1 exposes the minimal shape needed by the HTTP SPI; richer test/execution
 * context arrives with the context phase.</p>
 */
public interface RequestContext {

    /** Unique id of this request (generated by the framework). Never null. */
    String requestId();

    /** Correlation id linking this request to an external trace, if any. */
    Optional<String> correlationId();

    /** Immutable free-form metadata attached to this request. Never null. */
    Map<String, Object> metadata();

    /** New context with a random request id and no correlation id. */
    static RequestContext create() {
        return DefaultRequestContext.create();
    }

    /** New context with a random request id and the given correlation id (nullable). */
    static RequestContext withCorrelationId(String correlationId) {
        return DefaultRequestContext.withCorrelationId(correlationId);
    }
}
